FROM ubuntu:18.10
ADD frontend /home/spotapp/frontend
WORKDIR "/home/spotapp/frontend"

RUN apt-get update;
RUN apt-get install -y npm;
RUN npm install
RUN npm rebuild node-sass
ENTRYPOINT npm run build
